name: 'check-pr-title'
description: 'Check Pull Request Title'
branding:
  icon: "tag"
  color: "purple"
on: [pull_request]
outputs:
  RESULT:
    description: 'Verified Title Pull Request'
  DATA:
    description: 'ID JIRA'
runs:
  using: 'node12'
  main: 'dist/index.js'